//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MachineLearningSoftware.Views.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CleanDataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CleanDataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MachineLearningSoftware.Views.Properties.CleanDataResource", typeof(CleanDataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose File.
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Prediction Column.
        /// </summary>
        public static string ChoosePredictionColumn {
            get {
                return ResourceManager.GetString("ChoosePredictionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Data.
        /// </summary>
        public static string CleanData {
            get {
                return ResourceManager.GetString("CleanData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Prediction Values.
        /// </summary>
        public static string ColumnPredictionsTitle {
            get {
                return ResourceManager.GetString("ColumnPredictionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Data Visualisation.
        /// </summary>
        public static string DataVisualisationTitle {
            get {
                return ResourceManager.GetString("DataVisualisationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        public static string ExportData {
            get {
                return ResourceManager.GetString("ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Row Read.
        /// </summary>
        public static string LimitRowRead {
            get {
                return ResourceManager.GetString("LimitRowRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction Values.
        /// </summary>
        public static string PredictionValues {
            get {
                return ResourceManager.GetString("PredictionValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By Regular Expression.
        /// </summary>
        public static string RegexFilter {
            get {
                return ResourceManager.GetString("RegexFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Column Data Occurance Count.
        /// </summary>
        public static string SelectColumnDataOccurance {
            get {
                return ResourceManager.GetString("SelectColumnDataOccurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Column To Visualise.
        /// </summary>
        public static string SelectColumnToVisualise {
            get {
                return ResourceManager.GetString("SelectColumnToVisualise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Corrupt Values.
        /// </summary>
        public static string ShowCorruptValues {
            get {
                return ResourceManager.GetString("ShowCorruptValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Duplicates.
        /// </summary>
        public static string ShowDuplicates {
            get {
                return ResourceManager.GetString("ShowDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Prediction Values.
        /// </summary>
        public static string ShowPredictionValues {
            get {
                return ResourceManager.GetString("ShowPredictionValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualise Column.
        /// </summary>
        public static string VisualiseColumn {
            get {
                return ResourceManager.GetString("VisualiseColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualise Column Data.
        /// </summary>
        public static string VisualiseData {
            get {
                return ResourceManager.GetString("VisualiseData", resourceCulture);
            }
        }
    }
}
